#!/bin/bash
echo START mk_dock_image_force
AFLNM=`readlink -e "$0"`
WRDIR=`dirname "$AFLNM"`
SAVEDIR=$PWD
cd $WRDIR
. ./init_params


mkdir -p tmp


sed "/\LABEL Samba4 AD DC engine/a\ARG SMBVER=$VER\nARG PYVER=$PYVER " Dockerfile.tmpl >tmp/Dockerfile

cp install_in_dock_img tmp/install_in_dock_img
cd tmp

[ -e samba-$VER.tar.gz ]||wget https://download.samba.org/pub/samba/samba-$VER.tar.gz

DOCK_IMAGE=dtcentos/samba_dc:$VER

docker build --no-cache . -t  $DOCK_IMAGE
#docker push dtcentos/samba_dc:$VER
[ -e ../pushing_samba4 ]&&../pushing_samba4

rm -f samba-$VER.tar.gz

cd ..

echo DONE mk_dock_image_force
cd $SAVEDIR
