#!/bin/bash

DOMAIN=
USER=
if [ "$DOMAIN" = "" ]
 then
   echo Please Setup DOMAIN inside me
   exit
fi

if [ "$USER" = "" ]
 then
   echo Please Setup USER inside me
   exit
fi


docker exec -ti samba4dc \
/usr/local/samba/bin/samba-tool domain join $DOMAIN  DC -U$USER@$DOMAIN --realm=$DOMAIN

#/krb5.conf_tmpl $DOMAIN
#cho y|cp krb5.conf /etc/krb5.conf

