#!/bin/bash

DOMAIN=
USER=
DCNAME=
if [ "$DOMAIN" = "" ]
 then
   echo Please Setup DOMAIN inside me
   exit
fi

if [ "$USER" = "" ]
 then
   echo Please Setup USER inside me
   exit
fi


if [ "$DCNAME" = "" ]
 then
   echo Please Setup DCNAME inside me
   exit
fi



docker exec -ti samba4dc \
hostname $DCNAME||echo I\'m need running samba4dc container. Please run run_samba4_dock_no_daemon



docker exec -ti samba4dc \
/usr/local/samba/bin/samba-tool domain join $DOMAIN  DC -U$USER@$DOMAIN --realm=$DOMAIN||echo I\'m need running samba4dc container. Please run run_samba4_dock_no_daemon

docker kill samba4dc

#/krb5.conf_tmpl $DOMAIN
#cho y|cp krb5.conf /etc/krb5.conf

